export const mockData = {
  brands: [
    { id: 1, name: "Apple" },
    { id: 2, name: "Samsung" },
    { id: 3, name: "Dell" },
  ],
  categories: [
    { id: 1, name: "Điện thoại", brand_id: 1 },
    { id: 2, name: "Laptop", brand_id: 3 },
  ],
  products: [
    {
      id: 1,
      name: "iPhone 15 Pro Max",
      img: "/iphone-15-pro.jpg",
      amount: 50,
      created_at: "2024-01-15",
      description: "Điện thoại cao cấp với chip A17 Pro",
      cat_id: 1,
      brand_id: 1,
      brand: "Apple",
      category: "Điện thoại",
      images: ["/iphone-15-pro-1.jpg", "/iphone-15-pro-2.jpg", "/iphone-15-pro-3.jpg"],
      stock: 50,
      image: "/iphone-15-pro.jpg",
      price: 34990000,
    },
    {
      id: 2,
      name: "MacBook Pro 16",
      img: "/macbook.jpg",
      amount: 30,
      created_at: "2024-01-20",
      description: "Laptop chuyên nghiệp với chip M3 Max",
      cat_id: 2,
      brand_id: 1,
      brand: "Apple",
      category: "Laptop",
      images: ["/macbook.jpg"],
      stock: 30,
      image: "/macbook.jpg",
      price: 89990000,
    },
  ],
  configurations: [
    { id: 1, name: "256GB - Titan Tự Nhiên", price: 34990000, product_id: 1 },
    { id: 2, name: "512GB - Titan Xanh", price: 39990000, product_id: 1 },
    { id: 3, name: "32GB RAM - 1TB SSD", price: 89990000, product_id: 2 },
  ],
  specifications: [
    { id: 1, name: "RAM", value: "8GB", config_id: 1 },
    { id: 2, name: "Chip", value: "A17 Pro", config_id: 1 },
    { id: 3, name: "RAM", value: "8GB", config_id: 2 },
    { id: 4, name: "Chip", value: "A17 Pro", config_id: 2 },
    { id: 5, name: "CPU", value: "M3 Max", config_id: 3 },
    { id: 6, name: "GPU", value: "40-core", config_id: 3 },
  ],
  product_details: [
    { id: 1, product_id: 1, config_id: 1 },
    { id: 2, product_id: 1, config_id: 2 },
    { id: 3, product_id: 2, config_id: 3 },
  ],
  orders: [
    {
      id: 1,
      status: 2,
      purchase_date: "2024-01-25",
      payment_id: 1,
      admin_id: 1,
      customer_id: 1,
      customer_name: "Nguyễn Văn A",
      total: 34990000,
      order_date: "2024-01-25",
      phone: "0901234567",
      email: "nguyenvana@email.com",
      address: "123 Đường ABC, Quận 1, TP.HCM",
      status_text: "Đang giao",
      payment_method: "Thanh toán khi nhận hàng",
    },
    {
      id: 2,
      status: 1,
      purchase_date: "2024-01-26",
      payment_id: 1,
      admin_id: 1,
      customer_id: 2,
      customer_name: "Trần Thị B",
      total: 89990000,
      order_date: "2024-01-26",
      phone: "0907654321",
      email: "tranthib@email.com",
      address: "456 Đường XYZ, Quận 2, TP.HCM",
      status_text: "Chờ xử lý",
      payment_method: "Chuyển khoản ngân hàng",
    },
  ],
  order_details: [
    {
      id: 1,
      amount: 1,
      unit_price: 34990000,
      order_id: 1,
      pro_de_id: 1,
      product_name: "iPhone 15 Pro Max",
      config_name: "256GB - Titan Tự Nhiên",
      quantity: 1,
      price: 34990000,
      product_detail_id: 1,
    },
    {
      id: 2,
      amount: 1,
      unit_price: 89990000,
      order_id: 2,
      pro_de_id: 3,
      product_name: "MacBook Pro 16",
      config_name: "32GB RAM - 1TB SSD",
      quantity: 1,
      price: 89990000,
      product_detail_id: 3,
    },
  ],
  customers: [
    {
      id: 1,
      name: "Nguyễn Văn A",
      mail: "nguyenvana@email.com",
      address: "123 Đường ABC, Quận 1, TP.HCM",
      phone_number: "0901234567",
      total_spent: 34990000,
      orders_count: 1,
    },
    {
      id: 2,
      name: "Trần Thị B",
      mail: "tranthib@email.com",
      address: "456 Đường XYZ, Quận 2, TP.HCM",
      phone_number: "0907654321",
      total_spent: 89990000,
      orders_count: 1,
    },
  ],
  admins: [
    {
      id: 1,
      name: "Admin Chính",
      mail: "admin@store.com",
      address: "789 Đường Admin, Quận 3, TP.HCM",
      phone_number: "0909999999",
      role: "admin",
    },
    {
      id: 2,
      name: "Nhân Viên 1",
      mail: "nhanvien1@store.com",
      address: "321 Đường Staff, Quận 4, TP.HCM",
      phone_number: "0908888888",
      role: "employee",
    },
  ],
  payment_methods: [
    { id: 1, name: "Thanh toán khi nhận hàng" },
    { id: 2, name: "Chuyển khoản ngân hàng" },
  ],
  product_images: [
    { id: 1, product_id: 1, image_url: "/iphone-15-pro-1.jpg", is_main: true, order: 1 },
    { id: 2, product_id: 1, image_url: "/iphone-15-pro-2.jpg", is_main: false, order: 2 },
    { id: 3, product_id: 1, image_url: "/iphone-15-pro-3.jpg", is_main: false, order: 3 },
    { id: 4, product_id: 2, image_url: "/macbook.jpg", is_main: true, order: 1 },
  ],
}
